### ISSUE TITLE
Ability to chown provisioned datasets

### ISSUE THREAD

**Issue by gregwalters** [ccremer/kubernetes-zfs-provisioner#114]
When the zfs-provisioner runs it does not set the ownership information (uid/gid) on datasets that get created and this can cause pods running as non-root users to get permission errors writing to mounted volumes. 

Is it currently possible to specify UID/GID that should be applied to datasets upon creation? If not, it would be useful to be able to specify them either at the PVC level or as a default via the storageclass.

**Comment by ccremer** [comment]
Hi. Please see #74 and the reason why it isn't part of this project.
