### ISSUE TITLE
Build image with ARM support

### ISSUE THREAD

**Issue by michaelwoods** [ccremer/kubernetes-zfs-provisioner#6]
Would it be possible to add ARM64 images to your GitHub Action pipeline? I have an example [here](https://github.com/michaelwoods/onstar2mqtt/blob/4dd146b6b1519b5cc1b566f6d7459c7ab2f2e48d/.github/workflows/ci.yml#L54) for reference.

As-is, the pods immediately crash:
```
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by ccremer** [comment]
Hi
Sorry, I completely forgot this issue here.
I took some time today and experimented with docker manifest/buildx. I learned something new though :)

I've created PR #11 , the next release should feature image tags with arm64 support.
